// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSo-1jWstmBUIfIMyjSl29EBFPPqRBqXA',
    appId: '1:323736047715:web:d507e45739b319f48da856',
    messagingSenderId: '323736047715',
    projectId: 'myproject-d139b',
    authDomain: 'myproject-d139b.firebaseapp.com',
    databaseURL: 'https://myproject-d139b-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-d139b.appspot.com',
    measurementId: 'G-M5WB2RB35F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzupaRXyuOZbPXKjCcujfnUP_1kCIP4xA',
    appId: '1:323736047715:android:5b07f492f752bc4d8da856',
    messagingSenderId: '323736047715',
    projectId: 'myproject-d139b',
    databaseURL: 'https://myproject-d139b-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-d139b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_mUMH5LM2SYc60cZzUsBqHPS-bwdAEkM',
    appId: '1:323736047715:ios:51997b881d9317e08da856',
    messagingSenderId: '323736047715',
    projectId: 'myproject-d139b',
    databaseURL: 'https://myproject-d139b-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-d139b.appspot.com',
    iosClientId: '323736047715-5h5l9kbacriff8o6oin7b14q8jdcmr4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
